$(document).ready( function() {
setTooltip('#idNombre','Nombre del Complejo');
setTooltip('#idDescripcion','Descripci&oacute;n del Complejo');
setTooltip('#idDireccion','Direcci&oacute;n del Complejo');
setTooltip('#idNeighbourhood','Barrio del Complejo');
setTooltip('#idTown','Ciudad del Complejo');
setTooltip('#idState','Provincia del Complejo');
setTooltip('#idZipCode','C&oacute;digo Postal del Complejo');
setTooltip('#idLatitude','Latitud del Complejo');
setTooltip('#idLongitude','Longitud del Complejo');
setTooltip('#idTelephone','Tel&eacute;fono del Complejo');
$("#multiplePhone").click(function(){$("#divtelephone").append("<label for='telephone'> *Tel&eacute;fono</label><div id='divtelephone'><input id='idTelephone' type='text' name='telephone' value='1234-1232'  class='required'></div>")});
setTooltip('#idCountry','Pa&iacute;s del Complejo');
$("#idfecha_lunes_inicio").timepickr();
setTooltip('#idfecha_lunes_inicio','Hora de inicio');
$("#idfecha_lunes_fin").timepickr();
setTooltip('#idfecha_lunes_fin','Hora de cierre');
$("#idfecha_martes_inicio").timepickr();
setTooltip('#idfecha_martes_inicio','Hora de inicio');
$("#idfecha_martes_fin").timepickr();
setTooltip('#idfecha_martes_fin','Hora de cierre');
$("#idfecha_miercoles_inicio").timepickr();
setTooltip('#idfecha_miercoles_inicio','Hora de inicio');
$("#idfecha_miercoles_fin").timepickr();
setTooltip('#idfecha_miercoles_fin','Hora de cierre');
$("#idfecha_jueves_inicio").timepickr();
setTooltip('#idfecha_jueves_inicio','Hora de inicio');
$("#idfecha_jueves_fin").timepickr();
setTooltip('#idfecha_jueves_fin','Hora de cierre');
$("#idfecha_viernes_inicio").timepickr();
setTooltip('#idfecha_viernes_inicio','Hora de inicio');
$("#idfecha_viernes_fin").timepickr();
setTooltip('#idfecha_viernes_fin','Hora de cierre');
$("#idfecha_sabado_inicio").timepickr();
setTooltip('#idfecha_sabado_inicio','Hora de inicio');
$("#idfecha_sabado_fin").timepickr();
setTooltip('#idfecha_sabado_fin','Hora de cierre');
$("#idfecha_domingo_inicio").timepickr();
setTooltip('#idfecha_domingo_inicio','Hora de inicio');
$("#idfecha_domingo_fin").timepickr();
setTooltip('#idfecha_domingo_fin','Hora de cierre');
$("#formComplex").validate();
});